### ISSUE TITLE
Apiary error with Pipelines

### ISSUE THREAD

**Issue by perkincr** [jsynowiec/api-blueprint-boilerplate#6]
Hi, I am receiving an error when trying to publish to Apriary from Bitbucket Pipelines. Does the boilerplate still work? Has Apiary changed such that it is broken?

+ npm run publish
> api-blueprint-boilerplate@1.0.2 publish /opt/atlassian/pipelines/agent/build
> apiary publish --api-name="sprapi1" --path="api.apib"
/usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `parse': 784: unexpected token at '<!doctype html> (JSON::ParserError)
<html class="pageNon200">
<head>
  <meta charset="utf-8">
...
npm ERR! Tell the author that this fails on your system:
npm ERR!     apiary publish --api-name="sprapi1" --path="api.apib"

**Comment by jsynowiec** [comment]
Without seeing your blueprint I can't help much because I'm using those scripts without problem.

**Comment by perkincr** [comment]
Here is the blue print I'm attempting. If this works for you also, could it be the format of the variables such that the blueprint key is not being read properly?
[api.zip](https://github.com/jsynowiec/api-blueprint-boilerplate/files/1213556/api.zip)

**Comment by jsynowiec** [comment]
Can you just add it inline? Or link to a remote repository? I'm not going to download and extract an unknown zip archive ;)

**Comment by perkincr** [comment]
I was using my apib but switched to using the one in the boilerplate repository to test. 
https://github.com/jsynowiec/api-blueprint-boilerplate/blob/master/src/api.apib

Here is the information of the failed pipeline attempt to publish to apiary. It included an HTML response:

`+ npm run publish

> api-blueprint-boilerplate@1.0.2 publish /opt/atlassian/pipelines/agent/build
> apiary publish --api-name="sprapi1" --path="api.apib"

/usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `parse': 784: unexpected token at '<!doctype html> (JSON::ParserError)
<html class="pageNon200">
<head>
  <meta charset="utf-8">

  
  <title>Apiary - Server Error</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Apiary">
  <meta name="robots" content="NOINDEX,FOLLOW">
  <link rel="shortcut icon" href="https://static.apiary.io/assets/3aqvBs0H.ico">

    <script crossorigin="anonymous">window.webpackManifest = {"0":"0-68fed786.js","1":"1-68fed786.js","2":"2-68fed786.js","3":"3-68fed786.js","4":"4-68fed786.js","5":"5-68fed786.js","6":"6-68fed786.js","7":"7-68fed786.js","8":"8-68fed786.js","9":"9-68fed786.js","10":"10-68fed786.js","11":"11-68fed786.js","12":"12-68fed786.js","13":"13-68fed786.js","14":"14-68fed786.js","15":"15-68fed786.js","16":"16-68fed786.js","17":"17-68fed786.js","18":"18-68fed786.js","19":"19-68fed786.js","20":"20-68fed786.js","21":"21-68fed786.js","22":"22-68fed786.js","23":"23-68fed786.js"}</script><script src="https://static.apiary.io/assets/vendor-68fed786.js" crossorigin="anonymous"></script><script src="https://static.apiary.io/assets/error-68fed786.js" crossorigin="anonymous"></script>  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,600,600italic,700,700italic,300italic,300' rel='stylesheet' type='text/css'><link rel='stylesheet' crossorigin="anonymous" href="https://static.apiary.io/assets/error-19b5605a.css"></head>
<body class="website pageNon200 page500">

<div class="pageNon200nav">
  <div class="positioning">
    <a class="pageNon200logo" href="https://apiary.io"><span class="visuallyhidden">Apiary</span></a>
      </div>
</div>

<div class="pageNon200content">
  <div class="positioning">
    <div class="preLikeMessage">
    <span class="lineWrap"><span class="cKeyword">+ Response</span> <span class="cImportant">403</span> <span class="cInfo">(text/plain)</span></span>
    <span class="lineWrap">  </span>
    <span class="lineWrap multiLineMessage message">      Tokens scope must contain ALL or API_WRITE</span>
    <span class="lineWrap multiLineMessage">      Go to <a href="https://apiary.io">apiary homepage</a> or <a href="http://support.apiary.io">contact our support</a>.</span>
    </div>
  </div>
</div>


<footer class="applicationFooter">

  <div class="applicationFooterRow">
    <div class="applicationFooterColumns">
    <div class="applicationFooterColumn">
    </div><div class="applicationFooterColumn">
      <h3 class="applicationFooterTitle">Platform</h3>
      <ul class="applicationFooterList">
        <li><a class="applicationFooterListLink" href="https://apiary.io/how-apiary-works">How Apiary Works</a></li>
        <li><a class="applicationFooterListLink" href="https://apiary.io/products">Product</a></li>
        <li><a class="applicationFooterListLink" href="https://apiary.io/plans">Plans</a></li>
        <li><a class="applicationFooterListLink" href="https://help.apiary.io ">Help</a></li>
      </ul>
    </div><div class="applicationFooterColumn">
      <h3 class="applicationFooterTitle">Company</h3>
      <ul class="applicationFooterList">
        <li><a class="applicationFooterListLink" href="http://blog.apiary.io/">Blog</a></li>
        <li><a class="applicationFooterListLink" href="https://apiary.io/company">Team</a></li>
        <li><a class="applicationFooterListLink" href="https://apiary.io/jobs">Jobs</a></li>
        <li><a class="applicationFooterListLink" href="https://apiary.io/contact">Contact</a></li>
      </ul>
    </div><div class="applicationFooterColumn">
      <h3 class="applicationFooterTitle">Open Source</h3>
      <ul class="applicationFooterList">
        <li><a class="applicationFooterListLink" href="https://apiblueprint.org">API Blueprint</a></li>
        <li><a class="applicationFooterListLink" href="https://github.com/apiaryio/snowcrash">Snow Crash</a></li>
        <li><a class="applicationFooterListLink" href="https://github.com/apiaryio/gavel">Gavel</a></li>
        <li><a class="applicationFooterListLink" href="https://github.com/apiaryio/dredd">Dredd</a></li>
        <li><a class="applicationFooterListLink" href="https://docs.apiary.io/tools/apiary-cli/">Apiary CLI</a></li>
      </ul>
    </div><div class="applicationFooterColumn">
      <h3 class="applicationFooterTitle">Social</h3>
      <ul class="applicationFooterList">
        <li><a class="applicationFooterListLink" href="https://github.com/apiaryio">GitHub</a></li>
        <li><a class="applicationFooterListLink" href="https://twitter.com/apiaryio">Twitter</a></li>
        <li><a class="applicationFooterListLink" href="https://facebook.com/apiary.io">Facebook</a></li>
        <li><a class="applicationFooterListLink" href="https://plus.google.com/114367708466177247933/about">Google+</a></li>
        <li><a class="applicationFooterListLink" href="https://dribbble.com/apiary">Dribbble</a></li>
      </ul>
    </div></div>
  </div>

  <div class="applicationFooterRow">
    <p class="applicationFooterCopyright">
      Copyright &copy; 2017, Oracle and/or its affiliates. All rights reserved. Oracle and Java are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners.<span class="applicationFooterCopyrightLinks"> • <a href="https://apiary.io/tos" class="applicationFooterCopyrightLink">Terms</a> • <a href="https://apiary.io/privacy" class="applicationFooterCopyrightLink">Privacy</a></span>, Version: v3794    </p>
  </div>
</footer>


</body>
</html>
'
	from /usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /usr/local/bundle/gems/apiaryio-0.7.0/lib/apiary/command/publish.rb:86:in `rescue in query_apiary'
	from /usr/local/bundle/gems/apiaryio-0.7.0/lib/apiary/command/publish.rb:76:in `query_apiary'
	from /usr/local/bundle/gems/apiaryio-0.7.0/lib/apiary/command/publish.rb:53:in `publish_on_apiary'
	from /usr/local/bundle/gems/apiaryio-0.7.0/lib/apiary/command/publish.rb:41:in `execute'
	from /usr/local/bundle/gems/apiaryio-0.7.0/lib/apiary/cli.rb:45:in `publish'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/apiaryio-0.7.0/bin/apiary:5:in `<top (required)>'
	from /usr/local/bundle/bin/apiary:17:in `load'
	from /usr/local/bundle/bin/apiary:17:in `<main>'

npm ERR! Linux 4.11.11-coreos
npm ERR! argv "/root/.nvm/versions/node/v6.2.2/bin/node" "/root/.nvm/versions/node/v6.2.2/bin/npm" "run" "publish"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! api-blueprint-boilerplate@1.0.2 publish: `apiary publish --api-name="sprapi1" --path="api.apib"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api-blueprint-boilerplate@1.0.2 publish script 'apiary publish --api-name="sprapi1" --path="api.apib"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the api-blueprint-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     apiary publish --api-name="sprapi1" --path="api.apib"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs api-blueprint-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls api-blueprint-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/atlassian/pipelines/agent/build/npm-debug.log
`
